apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{ include "hlf-ordnode.name" . }}
      release: {{ .Release.Name }}
  # Ensure we allow our pod to be unavailable, so we can upgrade
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        checksum/configmap--ord: {{ include (print $.Template.BasePath "/configmap--ord.yaml") . | sha256sum | trunc 60 }}
        checksum/configmap--ord--core: {{ include (print $.Template.BasePath "/configmap--ord--core.yaml") . | sha256sum | trunc 60 }}
        checksum/config-ou: {{ include (print $.Template.BasePath "/config-ou.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--orderer0-admin: {{ include (print $.Template.BasePath "/secret--orderer0-admin.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--orderer0-idcert: {{ include (print $.Template.BasePath "/secret--orderer0-idcert.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--orderer0-idkey: {{ include (print $.Template.BasePath "/secret--orderer0-idkey.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--orderer0-tls: {{ include (print $.Template.BasePath "/secret--orderer0-tls.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--ordererorg-cacert: {{ include (print $.Template.BasePath "/secret--ordererorg-cacert.yaml") . | sha256sum | trunc 60 }}
        checksum/secret--ordererorg-tlsrootcert: {{ include (print $.Template.BasePath "/secret--ordererorg-tlsrootcert.yaml") . | sha256sum | trunc 60 }}
{{ include "labels.standard" . | indent 8 }}
    spec:
      hostAliases:
{{ toYaml .Values.hostAliases | indent 10 }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "hlf-ordnode.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: id-cert
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-idcert
        - name: id-key
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-idkey
        - name: cacert
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-cacert
        - name: tls
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-tls
        - name: tls-rootcert
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-tlsrootcert
        - name: tls-clientrootcert
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-peer-tlsrootcert
        - name: genesis
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}--genesis
        {{- if .Values.channelParticipationEnabled }}
        - name: admin
          secret:
            secretName: {{ include "hlf-ordnode.fullname" . }}-admin
        {{- end }}

        - name: nodeou
          configMap:
            name: '{{ include "hlf-ordnode.fullname" . }}-nodeou'
            items:
              - key: 'config.yaml'
                path: 'config.yaml'
        - name: config
          configMap:
            name: '{{ include "hlf-ordnode.fullname" . }}--orderer--core'
            items:
              - key: 'orderer.yaml'
                path: 'orderer.yaml'
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
{{ if .Values.proxy.enabled}}
        - name: grpc-web
          image: "{{.Values.proxy.image}}:{{.Values.proxy.tag}}"
          ports:
            - containerPort: 7443
              name: grpc-web
              protocol: TCP
          resources:
{{ toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/hyperledger/tls/server/pair
              name: tls
            - mountPath: /var/hyperledger/tls/server/cert
              name: tls-rootcert
          env:
            - name: BACKEND_ADDRESS
              value: "127.0.0.1:7050"
            - name: SERVER_TLS_CERT_FILE
              value: "/var/hyperledger/tls/server/pair/tls.crt"
            - name: SERVER_TLS_KEY_FILE
              value: "/var/hyperledger/tls/server/pair/tls.key"
            - name: BACKEND_TLS_CA_FILES
              value: "/var/hyperledger/tls/server/cert/cacert.pem"
            - name: SERVER_BIND_ADDRESS
              value: "0.0.0.0"
            - name: SERVER_HTTP_DEBUG_PORT
              value: "8080"
            - name: SERVER_HTTP_TLS_PORT
              value: "7443"
            - name: BACKEND_TLS
              value: "true"
            - name: SERVER_HTTP_MAX_WRITE_TIMEOUT
              value: "5m"
            - name: SERVER_HTTP_MAX_READ_TIMEOUT
              value: "5m"
            - name: USE_WEBSOCKETS
              value: "true"
{{ end }}
        - name: orderer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ord-port
              containerPort: 7050
              protocol: TCP
            - name: ord-operations
              containerPort: 9444
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9444
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9444
            initialDelaySeconds: 15
          command:
            - sh
            - -c
            - |

              while [ ! -d /hl_config/genesis ] || [ -z "$(ls -A /hl_config/genesis)" ];
              do
                echo "\033[0;31m /hl_config/genesis must contain Genesis transaction \033[0m"
                sleep 60
              done

              while [ ! -d ${ORDERER_GENERAL_LOCALMSPDIR}/signcerts ];
              do
                echo "\033[0;31m ${ORDERER_GENERAL_LOCALMSPDIR}/signcerts directory must exist \033[0m"
                sleep 60
              done
              mkdir -p /var/hyperledger/msp/admincerts

              echo "\033[0;32m Create ${ORDERER_FILELEDGER_LOCATION} directory to avoid restarts \033[0m"
              mkdir -p ${ORDERER_FILELEDGER_LOCATION}
              mkdir -p ${ORDERER_FILELEDGER_LOCATION}/index

              if [ $ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED ]
              then
                export ORDERER_GENERAL_TLS_CLIENTROOTCAS=$(echo $(ls $ORDERER_GENERAL_TLS_CLIENTROOTCAS) | echo "[$(sed 's/ /,/g')]")
              fi

              echo ">\033[0;35m orderer \033[0m"
              orderer

          {{- if $.Values.envVars }}
          env:
{{ toYaml .Values.envVars | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "hlf-ordnode.fullname" . }}--ord
          volumeMounts:
            - mountPath: /var/hyperledger
              name: data
            - mountPath: /var/hyperledger/msp/signcerts
              name: id-cert
            - mountPath: /var/hyperledger/msp/keystore
              name: id-key
            - mountPath: /var/hyperledger/msp/cacerts
              name: cacert
            - mountPath: /var/hyperledger/admin_msp/cacerts
              name: cacert
            - mountPath: /var/hyperledger/fabric/config
              name: config

            - mountPath: /var/hyperledger/msp/config.yaml
              name: nodeou
              subPath: config.yaml

            - mountPath: /var/hyperledger/tls/server/pair
              name: tls
            - mountPath: /var/hyperledger/tls/server/cert
              name: tls-rootcert
            - mountPath: /var/hyperledger/tls/client/cert
              name: tls-clientrootcert
            - mountPath: /hl_config/genesis
              name: genesis
          {{- if .Values.channelParticipationEnabled }}
            - mountPath: /var/hyperledger/admin
              name: admin
          {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
