kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30949
        hostPort: 80
      - containerPort: 30950
        hostPort: 443
