apiVersion: v1
description: Hyperledger Fabric Orderer chart
name: hlf-ord
version: 1.4.0
appVersion: 1.4.3
keywords:
  - blockchain
  - hyperledger
  - fabric
home: http://hyperledger-fabric.readthedocs.io
sources:
  - https://github.com/hyperledger/fabric
icon: https://www.hyperledger.org/wp-content/uploads/2018/04/fabric-logo.png
