apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}-tls
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key  | b64enc | quote }}