---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: fabricfollowerchannels.hlf.kungfusoftware.es
spec:
  group: hlf.kungfusoftware.es
  names:
    kind: FabricFollowerChannel
    listKind: FabricFollowerChannelList
    plural: fabricfollowerchannels
    shortNames:
      - fabricfollowerchannel
    singular: fabricfollowerchannel
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.status
          name: State
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: FabricFollowerChannel is the Schema for the hlfs API
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: FabricFollowerChannelSpec defines the desired state of FabricFollowerChannel
              properties:
                anchorPeers:
                  description: Anchor peers defined for the current organization
                  items:
                    properties:
                      host:
                        description: Host of the anchor peer
                        type: string
                      port:
                        description: Port of the anchor peer
                        type: integer
                    required:
                      - host
                      - port
                    type: object
                  type: array
                externalPeersToJoin:
                  description: Peers to join the channel
                  items:
                    properties:
                      tlsCACert:
                        description: FabricPeer TLS CA certificate of the peer
                        type: string
                      url:
                        description: FabricPeer URL of the peer
                        type: string
                    required:
                      - tlsCACert
                      - url
                    type: object
                  type: array
                hlfIdentity:
                  description: Identity to use to interact with the peers and the orderers
                  properties:
                    secretKey:
                      description: Key inside the secret that holds the private key and certificate to interact with the network
                      type: string
                    secretName:
                      description: Secret name
                      type: string
                    secretNamespace:
                      default: default
                      description: Secret namespace
                      type: string
                  required:
                    - secretKey
                    - secretName
                    - secretNamespace
                  type: object
                mspId:
                  description: MSP ID of the organization to join the channel
                  type: string
                name:
                  description: Name of the channel
                  type: string
                orderers:
                  description: Orderers to fetch the configuration block from
                  items:
                    properties:
                      certificate:
                        description: TLS Certificate of the orderer node
                        type: string
                      url:
                        description: 'URL of the orderer, e.g.: "grpcs://xxxxx:443"'
                        type: string
                    required:
                      - certificate
                      - url
                    type: object
                  type: array
                peersToJoin:
                  description: Peers to join the channel
                  items:
                    properties:
                      name:
                        description: FabricPeer Name of the peer inside the kubernetes cluster
                        type: string
                      namespace:
                        description: FabricPeer Namespace of the peer inside the kubernetes cluster
                        type: string
                    required:
                      - name
                      - namespace
                    type: object
                  type: array
              required:
                - anchorPeers
                - externalPeersToJoin
                - hlfIdentity
                - mspId
                - name
                - orderers
                - peersToJoin
              type: object
            status:
              description: FabricFollowerChannelStatus defines the observed state of FabricFollowerChannel
              properties:
                conditions:
                  description: Conditions is a set of Condition instances.
                  items:
                    description: "Condition represents an observation of an object's state. Conditions are an extension mechanism intended to be used when the details of an observation are not a priori known or would not apply to all instances of a given Kind. \n Conditions should be added to explicitly convey properties that users and components care about rather than requiring those properties to be inferred from other observations. Once defined, the meaning of a Condition can not be changed arbitrarily - it becomes part of the API, and has the same backwards- and forwards-compatibility concerns of any other part of the API."
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      reason:
                        description: ConditionReason is intended to be a one-word, CamelCase representation of the category of cause of the current status. It is intended to be used in concise output, such as one-line kubectl get output, and in summarizing occurrences of causes.
                        type: string
                      status:
                        type: string
                      type:
                        description: "ConditionType is the type of the condition and is typically a CamelCased word or short phrase. \n Condition types should indicate state in the \"abnormal-true\" polarity. For example, if the condition indicates when a policy is invalid, the \"is valid\" case is probably the norm, so the condition should be called \"Invalid\"."
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                message:
                  type: string
                status:
                  description: Status of the FabricCA
                  type: string
              required:
                - conditions
                - message
                - status
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
